### ISSUE TITLE
Command to git clone does not work on my dev box

### ISSUE THREAD

**Issue by stevefengjin** [OfficeDev/Word-Scenario-based-Add-in-Samples#12]
Repro steps:
1. Visit https://github.com/OfficeDev/Word-Scenario-based-Add-in-Samples/tree/main/Word-Add-in-AIGC
2. Locate the instruction "Manually run on your local machine"
3. Copy the command to my local PowerShell to run "git clone https://github.com/OfficeDev/Word-Scenario-based-Add-in-Samples.git && cd Word-Scenario-based-Add-in-Samples/Word-Add-in-AIGC && npm install" 
4. Ran into error as shown in attached screenshot.

<img width="616" alt="Screenshot 2023-12-07 112124" src="https://github.com/OfficeDev/Word-Scenario-based-Add-in-Samples/assets/151117136/c510c2ea-e4ad-4d90-8241-cb87c589a55c">

FWIW, if I break the command to three separate commands in 3 lines:
git clone https://github.com/OfficeDev/Word-Scenario-based-Add-in-Samples.git
cd Word-Scenario-based-Add-in-Samples/Word-Add-in-AIGC
npm install

They can work ok.

**Comment by ZYUN-MSFT** [comment]
Hi @stevefengjin ,

Thanks for reaching out to us. For the question you describe, I assume that you are using the Powershell with version lower than 7.

The operater `&&` is only avaliable in Powershell 7+ version (which also called pwsh), you can see the detail in this [Doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipeline_chain_operators?view=powershell-7.4).

BTW, you can use `$PSVersionTable.PSVersion` to see the Powershell version you used.

Thanks.

**Comment by stevefengjin** [comment]
> Hi @stevefengjin ,
> 
> Thanks for reaching out to us. For the question you describe, I assume that you are using the Powershell with version lower than 7.
> 
> The operater `&&` is only avaliable in Powershell 7+ version (which also called pwsh), you can see the detail in this [Doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipeline_chain_operators?view=powershell-7.4).
> 
> BTW, you can use `$PSVersionTable.PSVersion` to see the Powershell version you used.
> 
> Thanks.

Thanks @ZYUN-MSFT, yes, my local Powershell is v5.1, and I think the readme should be clear on those prerequisites.
